export const GET_ITEMS = 'GET_ITEMS';
export const SET_SHAPE_FILTER = 'SET_SHAPE_FILTER';
export const GET_SHAPE_FILTER = 'GET_SHAPE_FILTER';
export const SET_COLOR_FILTER = 'SET_COLOR_FILTER';
export const GET_COLOR_FILTER = 'GET_COLOR_FILTER';